load("@io_bazel_rules_scala//scala:scala.bzl", "scala_library")

scala_library(
    name = "2nd_party_example",
    srcs = [
        "SecondPartyExample.scala",
        ],
    visibility = ["//visibility:public"],
)